SET TIME ZONE 'UTC';

DROP VIEW IF EXISTS behavior_clean;
DROP TABLE IF EXISTS dim_category;
DROP TABLE IF EXISTS dim_item;
DROP TABLE IF EXISTS dim_user;
DROP TABLE IF EXISTS behavior;

CREATE TABLE behavior (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    behavior_type TEXT NOT NULL,
    timestamps BIGINT NOT NULL
);

CREATE INDEX idx_behavior_user
    ON behavior (user_id, timestamps);

CREATE INDEX idx_behavior_category
    ON behavior (category_id, timestamps);

CREATE INDEX idx_behavior_category_user
    ON behavior (category_id, user_id);

CREATE INDEX idx_behavior_item_user
    ON behavior (item_id, user_id);

CREATE INDEX idx_behavior_time
    ON behavior (timestamps);

CREATE INDEX idx_behavior_type_time
    ON behavior (behavior_type, timestamps);

CREATE INDEX idx_behavior_type_user
    ON behavior (behavior_type, user_id);

CREATE VIEW behavior_clean AS
SELECT
    id,
    user_id,
    item_id,
    category_id,
    behavior_type,
    timestamps,
    TO_CHAR(
        TO_TIMESTAMP(timestamps::DOUBLE PRECISION)
            AT TIME ZONE 'Asia/Shanghai',
        'YYYY-MM-DD'
    ) AS event_day,
    EXTRACT(
        HOUR FROM
        TO_TIMESTAMP(timestamps::DOUBLE PRECISION)
            AT TIME ZONE 'Asia/Shanghai'
    )::INT AS event_hour
FROM behavior
WHERE TO_CHAR(
    TO_TIMESTAMP(timestamps::DOUBLE PRECISION)
        AT TIME ZONE 'Asia/Shanghai',
    'YYYY-MM-DD'
) BETWEEN '2017-11-25' AND '2017-12-03';

CREATE TABLE dim_user (
    user_id BIGINT PRIMARY KEY,
    behavior_count BIGINT NOT NULL,
    active_days INTEGER NOT NULL,
    first_ts BIGINT NOT NULL,
    last_ts BIGINT NOT NULL
);

CREATE TABLE dim_item (
    item_id BIGINT PRIMARY KEY,
    behavior_count BIGINT NOT NULL,
    user_count BIGINT NOT NULL
);

CREATE TABLE dim_category (
    category_id BIGINT PRIMARY KEY,
    behavior_count BIGINT NOT NULL,
    user_count BIGINT NOT NULL
);
